<a href="https://colab.research.google.com/github/jaylen-shen/820Jaylen/blob/main/DPO_%E5%BE%AE%E8%B0%83%EF%BC%9A%E6%A0%B9%E6%8D%AE%E5%81%8F%E5%A5%BD%E5%BC%95%E5%AF%BCLLM%E7%9A%84%E8%BE%93%E5%87%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install trl
import os
import re
import json

import torch
import pandas as pd
from tqdm.auto import tqdm

from datasets import Dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, GenerationConfig
from trl import DPOConfig, DPOTrainer

# 完整更新环境
!pip install -U transformers accelerate bitsandbytes

Requirement already satisfied: trl in /usr/local/lib/python3.11/dist-packages (0.19.1)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from trl) (1.9.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from trl) (4.0.0)
Requirement already satisfied: transformers>=4.51.0 in /usr/local/lib/python3.11/dist-packages (from trl) (4.53.2)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (2.6.0+cu124)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (0.33.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate>=1.4.0->trl) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets>=3.0.0->trl) (0.70.15)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.51.0->trl) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.51.0->trl) (0.21.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2025.7.14)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate>=1.4.0->trl) (3.0.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.9.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.11/dist-packages (0.46.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.33.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.6.0+cu124)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.7.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)

In [ ]:
!git clone https://github.com/Baiiiiiiiiii/GenAI_hw6_dataset.git

fatal: destination path 'GenAI_hw6_dataset' already exists and is not an empty directory.

In [ ]:
import os
import re
import json

import torch
import pandas as pd
from tqdm.auto import tqdm

from datasets import Dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, GenerationConfig
from trl import DPOConfig, DPOTrainer

with open("./GenAI_hw6_dataset/labelled_data.json", 'r') as jsonfile:
    full_data = json.load(jsonfile)

with open("./GenAI_hw6_dataset/test_prompt.json", 'r') as jsonfile:
    test_data = json.load(jsonfile)

In [ ]:
model = AutoModelForCausalLM.from_pretrained(
    'MediaTek-Research/Breeze-7B-Instruct-v0_1',
    device_map='auto',
    trust_remote_code=True,
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type='nf4'
    )
)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('MediaTek-Research/Breeze-7B-Instruct-v0_1')
# 本地取消下面的注释，然后注释上面
# tokenizer = AutoTokenizer.from_pretrained('Breeze-7B-Instruct-v0_1')
tokenizer.padding_side = "right"
tokenizer.pad_token = tokenizer.eos_token

def data_formulate(data):
    messages = [
        {"role": "system", "content": '回覆請少於20字'},
        {"role": "user", "content": data['prompt']},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    return prompt

original_model_response = []
for data in tqdm(test_data):
    id = data['id']
    print(f"Question {id}:\n{data['prompt']}")

    inputs = tokenizer(data_formulate(data), return_tensors="pt").to('cuda')
    generation_config = GenerationConfig(
        do_sample=False,
        max_new_tokens=200,
        pad_token_id=tokenizer.pad_token_id
    )
    output = model.generate(**inputs, generation_config=generation_config)
    output_text = tokenizer.batch_decode(output, skip_special_tokens=True)[0].split('[/INST] ')[1]
    original_model_response.append(output_text)

    print(f"Response from original model:\n{output_text}\n")

  0%|          | 0/10 [00:00<?, ?it/s]

Question 1:
真人化是否能改善日本漫畫的全球可及性？

  0%|          | 0/10 [00:00<?, ?it/s]

RuntimeError: expected scalar type BFloat16 but found Float

In [ ]:
num_epoch = 3      # 训练轮数
data_size = 50      # 用于训练的数据量
support_ratio = 0.1 # 偏好支持真人化的比例

In [ ]:
# 选择部分数据用于训练
training_data = full_data[:data_size]

# 定义 support 数据集的大小，用于将一部分数据标记为“支持” (chosen)，另一部分标记为“反对” (rejected)
support_data_size = int(data_size * support_ratio)

# 为训练数据集准备数据
prompt_list = [data_formulate(data) for data in training_data]
chosen_list = [data['support'] for data in training_data[:support_data_size]] + [data['oppose'] for data in training_data[support_data_size:]]
rejected_list = [data['oppose'] for data in training_data[:support_data_size]] + [data['support'] for data in training_data[support_data_size:]]
position_list = ['support' for _ in range(support_data_size)] + ['oppose' for _ in range(data_size - support_data_size)]

# 创建训练数据集
train_dataset = Dataset.from_dict({'prompt': prompt_list, 'position': position_list, 'chosen': chosen_list, 'rejected': rejected_list})
pd.DataFrame(train_dataset).rename(columns={"chosen": "preferred", "rejected": "non-preferred"})

,prompt,position,preferred,non-preferred
0,<s>回覆請少於20字 [INST] 日本動漫真人化是否有損原作形象？ [/INST],support,真人化能夠呈現更真實的角色形象，提升原作魅力。,真人化可能無法完美呈現動畫中的獨特風格，損害原作形象。
1,<s>回覆請少於20字 [INST] 真人化是否能夠擴大動漫在全球的影響力？ [/INST],support,真人化能夠讓更多非動漫迷接觸作品，擴大影響力。,真人化可能失去動漫的獨特風格，限制影響力擴大。
2,<s>回覆請少於20字 [INST] 真人化是否能夠吸引新觀眾？ [/INST],support,真人化能夠吸引不熟悉動漫的觀眾，擴大受眾。,真人化可能讓原本的動漫迷感到失望，無法吸引新觀眾。
3,<s>回覆請少於20字 [INST] 真人化是否能夠保留原作故事情節的精髓？ [/INST],support,真人化有機會更深入挖掘原作故事，保留精髓。,真人化可能因為改編而失去原作故事的深度與精髓。
4,<s>回覆請少於20字 [INST] 真人化是否能夠提升動漫產業的商業價值？ [/INST],support,真人化能夠開拓更多商業機會，提升產業價值。,真人化可能讓觀眾對原作失去興趣，影響產業價值。
5,<s>回覆請少於20字 [INST] 真人化是否能夠保持原作的文化特色？ [/INST],oppose,真人化可能因為文化差異而失去原作獨有的文化魅力。,真人化可以透過場景、服裝等元素保留文化特色。
6,<s>回覆請少於20字 [INST] 真人化是否能夠挑戰技術上的新突破？ [/INST],oppose,真人化可能因為技術限制而無法達到動畫中的視覺效果。,真人化促使技術創新，挑戰視覺效果上的新高度。
7,<s>回覆請少於20字 [INST] 真人化是否會受到演員選擇的爭議？ [/INST],oppose,演員選擇可能引起爭議，觀眾難以接受角色塑造。,演員選擇可因應市場需求，不必受限於動畫形象。
8,<s>回覆請少於20字 [INST] 真人化是否能夠提高動漫的社會認同度？ [/INST],oppose,真人化可能因為劇情改編而無法贏得社會認同。,真人化有機會讓更多人接受動漫，提高社會認同度。
9,<s>回覆請少於20字 [INST] 真人化是否能夠保留原作角色的個性特色？ [/INST],oppose,真人化可能因演員演技或導演選擇而失去角色的原有特色。,真人化可以透過演員表現保留角色的個性特色。
10,<s>回覆請少於20字 [INST] 真人化是否會影響原作動畫的收視率？ [/INST],oppose,真人化可能因為原作粉絲的反感而影響動畫收視率。,真人化可能吸引更廣泛的觀眾群，提高收視率。
11,<s>回覆請少於20字 [INST] 真人化是否會受到版權問題的困擾？ [/INST],oppose,版權問題可能成為真人化的阻礙，影響製作進程。,版權問題可透過合作與協商解決，不一定成為問題。
12,<s>回覆請少於20字 [INST] 真人化是否會引起文化觀念差異的爭議？ [/INST],oppose,真人化可能因文化觀念差異引起爭議，影響觀眾接受度。,透過適度的改編，真人化可減少文化觀念差異的爭議。
13,<s>回覆請少於20字 [INST] 真人化是否能夠挑戰影片表現的新風格？ [/INST],oppose,真人化可能受制於原作風格，難以創造新的影片風格。,真人化有機會探索新的視覺風格，豐富影片表現。
14,<s>回覆請少於20字 [INST] 真人化是否能夠推動動漫產業的多元發展？ [/INST],oppose,真人化可能使觀眾對原作產生固有印象，難以多元發展。,真人化能夠開啟動漫產業的多元化發展方向。
15,<s>回覆請少於20字 [INST] 真人化是否會改變原作動畫的風格？ [/INST],oppose,真人化可能難以完美呈現原作動畫獨有的視覺風格。,真人化可以透過改編風格，呈現不同的視覺風格。
16,<s>回覆請少於20字 [INST] 真人化是否能夠擴大原作的世界觀？ [/INST],oppose,真人化可能因製作預算或技術限制無法展現原作的豐富世界觀。,真人化有機會透過實景呈現，擴大原作的世界觀。
17,<s>回覆請少於20字 [INST] 真人化是否能夠吸引更多投資進入動漫產業？ [/IN...,oppose,真人化可能因觀眾反感而使投資者對動漫產業失去信心。,真人化能夠讓更多投資者看到商機，增加投資動機。
18,<s>回覆請少於20字 [INST] 真人化是否能夠促進原作動畫的衍生品銷售？ [/IN...,oppose,真人化可能因觀眾對原作失望而降低衍生品銷售。,真人化能夠擴大原作品牌影響力，提高衍生品銷售。
19,<s>回覆請少於20字 [INST] 真人化是否能夠提升動漫的社會地位？ [/INST],oppose,真人化可能讓觀眾對動漫產生負面印象，降低社會地位。,真人化有機會使動漫更受社會重視，提升地位。
20,<s>回覆請少於20字 [INST] 真人化是否會破壞原作動畫的獨特性？ [/INST],oppose,真人化可能因為改編而使原作失去獨特風格。,真人化可以透過新的呈現方式，保留原作的獨特性。
21,<s>回覆請少於20字 [INST] 真人化是否能夠促進動漫產業的國際交流？ [/INST],oppose,真人化可能因文化差異而難以打開國際市場，限制交流。,真人化能夠使動漫更容易被國際觀眾理解，促進交流。
22,<s>回覆請少於20字 [INST] 真人化是否會影響原作動畫的經典地位？ [/INST],oppose,真人化可能因改編而被視為是對原作經典的不敬。,真人化可以為原作注入新活力，提升經典地位。
23,<s>回覆請少於20字 [INST] 真人化是否會受到粉絲的反感？ [/INST],oppose,部分粉絲可能因真人化而感到失望，產生強烈反感。,部分粉絲可能因真人化而感到新鮮，不一定反感。
24,<s>回覆請少於20字 [INST] 真人化是否能夠挖掘原作未探索的劇情？ [/INST],oppose,真人化可能因為劇情改編而失去原作的深度與探索價值。,真人化有機會透過改編劇情，挖掘原作未探索的內容。
25,<s>回覆請少於20字 [INST] 真人化是否能夠吸引更多知名導演與演員參與？ [/I...,oppose,真人化可能因為風險高而難以吸引知名導演與演員參與。,真人化能夠吸引更多知名人士參與，提升製作水平。
26,<s>回覆請少於20字 [INST] 真人化是否會受到動畫粉絲的期待壓力？ [/INST],oppose,真人化可能因無法滿足動畫粉絲的期待而受到極大壓力。,真人化可以透過適度的改編滿足觀眾期待，降低壓力。
27,<s>回覆請少於20字 [INST] 真人化是否有助於促進動漫產業內的技術創新？ [/I...,oppose,過分專注於真人化可能會忽視動漫本身的技術創新和發展。,真人化的製作需求推動了視覺效果和製作技術的創新。
28,<s>回覆請少於20字 [INST] 真人化是否會提高動漫文化的普及和接受度？ [/IN...,oppose,真人化可能會降低動漫文化的獨特性，減少其對特定群體的吸引力。,真人化有助於使動漫文化更加普及，吸引更多不同背景的觀眾。
29,<s>回覆請少於20字 [INST] 真人化是否有助於提升動漫角色的深度和多維度？ [/...,oppose,真人化經常無法徹底展現動漫角色的複雜性和深度。,真人演員的演繹能為動漫角色增添更多層次和深度。
30,<s>回覆請少於20字 [INST] 真人化能增加原作的知名度嗎？ [/INST],oppose,真人化經常失敗，可能損害原作的聲譽。,真人化能擴大原作的觀眾群，提高其知名度。
31,<s>回覆請少於20字 [INST] 真人化能夠提高原作的藝術價值嗎？ [/INST],oppose,真人化往往無法捕捉原作的藝術魅力，反而貶低其價值。,真人化是對原作的新詮釋，能增加其藝術層面的深度。
32,<s>回覆請少於20字 [INST] 真人化是否利於動漫產業的經濟發展？ [/INST],oppose,真人化的商業化導向可能扭曲原作精神，對產業長期發展不利。,真人化能創造新的商業機會，刺激動漫產業的經濟增長。
33,<s>回覆請少於20字 [INST] 真人化是否有助於動漫文化的國際傳播？ [/INST],oppose,真人化可能會錯誤詮釋動漫文化，造成國際上的誤解。,真人化作品更容易被國際觀眾接受，有助於推廣動漫文化。
34,<s>回覆請少於20字 [INST] 真人化是否能準確再現動漫的奇幻元素？ [/INST],oppose,真人化往往無法完美再現動漫的奇幻世界，失去原作魅力。,現代技術能夠精準再現動漫的奇幻元素，增強真人化的吸引力。
35,<s>回覆請少於20字 [INST] 真人化是否尊重原作的精神和內容？ [/INST],oppose,真人化經常為了商業利益而改變原作的核心精神和內容。,真人化時，製作團隊通常會努力保持對原作的忠誠和尊重。
36,<s>回覆請少於20字 [INST] 真人化對原作的完整性有何影響？ [/INST],oppose,真人化往往簡化或改變原作的故事，損害其完整性。,真人化為原作提供了新的視角，豐富了其敘事和背景。
37,<s>回覆請少於20字 [INST] 真人化是否有助於吸引更廣泛的觀眾群？ [/INST],oppose,真人化可能會失去核心動漫粉絲，而無法吸引新觀眾。,真人化能吸引不習慣看動漫的觀眾，擴大受眾基礎。
38,<s>回覆請少於20字 [INST] 真人化是否有助於提升原創動漫的品牌價值？ [/IN...,oppose,不成功的真人化可能損害原創動漫的品牌形象。,成功的真人化能提升原創動漫的品牌價值和市場認可。
39,<s>回覆請少於20字 [INST] 真人化是否有助於促進原創作者的創意表達？ [/IN...,oppose,真人化可能限制或扭曲原創者的創意，使其不再忠實於原作。,真人化提供了一個新平台，讓原創作者能夠以不同方式表達創意。
40,<s>回覆請少於20字 [INST] 真人化是否會增加原作的文化影響力？ [/INST],oppose,真人化可能會稀釋原作的獨特文化元素，降低其影響力。,真人化作品更容易被主流文化接受，增強原作的文化影響力。
41,<s>回覆請少於20字 [INST] 真人化是否有助於原作故事的深度和複雜度？ [/IN...,oppose,真人化經常因時長和預算限制而簡化故事，減少深度和複雜度。,真人化可以加深原作的敘事深度，提供更複雜的角色和情節發展。
42,<s>回覆請少於20字 [INST] 真人化是否有助於動漫產業的多元化發展？ [/INST],oppose,過度專注於真人化可能會忽視動漫其他領域的發展，限制多元化。,真人化作品的多樣性能推動整個動漫產業向更多元化方向發展。
43,<s>回覆請少於20字 [INST] 真人化是否有助於提高原作的國際競爭力？ [/INST],oppose,真人化如果失敗，可能會損害原作在國際市場的聲譽和競爭力。,真人化能使原作更容易進入國際市場，提高其全球競爭力。
44,<s>回覆請少於20字 [INST] 真人化是否有助於原創作者的經濟利益？ [/INST],oppose,真人化可能會未經原創者充分同意就進行，侵犯其經濟和版權利益。,真人化的成功能為原創者帶來額外的經濟收益。
45,<s>回覆請少於20字 [INST] 真人化是否有助於促進動漫和其他媒介的合作？ [/I...,oppose,過分依賴真人化可能會忽視動漫本身的獨立性和特色，限制媒介間的真正合作。,真人化能開啟與電影、電視等其他媒介的合作機會。
46,<s>回覆請少於20字 [INST] 真人化是否有助於拓寬動漫的故事敘述方式？ [/IN...,oppose,真人化往往受限於現實條件，無法像動漫那樣自由發揮故事敘述。,真人化提供了一種全新的敘述方式，豐富動漫的故事表達。
47,<s>回覆請少於20字 [INST] 真人化是否有助於提高動漫角色的真實感？ [/INST],oppose,真人化往往無法完全捕捉到動漫角色的獨特魅力和特性。,真人演員能賦予動漫角色更多人性化和真實感。
48,<s>回覆請少於20字 [INST] 真人化是否能夠正確傳達原作的主題和信息？ [/IN...,oppose,真人化經常因為格式和風格限制而失去傳達原作主題的能力。,真人化能夠通過實際演繹更加生動地傳達原作的主題和信息。
49,<s>回覆請少於20字 [INST] 真人化是否有助於增進原創動漫的社會認知度？ [/I...,oppose,真人化可能會將動漫文化簡化，降低其在社會中的地位和認知度。,真人化能使原創動漫更容易獲得主流社會的認可和關注。

In [ ]:
training_args = DPOConfig(
    output_dir='./',
    per_device_train_batch_size=1,
    num_train_epochs=num_epoch,
    gradient_accumulation_steps=8,
    gradient_checkpointing=False,
    learning_rate=2e-4,
    optim="paged_adamw_8bit",
    logging_steps = 1,
    warmup_ratio = 0.1,
    beta=0.1,
    report_to = 'none',

    # 显式声明以避免报错
    max_length=512,
    max_prompt_length=128,
    remove_unused_columns=False,
)

In [ ]:
peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM",
)

In [ ]:
dpo_trainer = DPOTrainer(
    model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=tokenizer,
    peft_config=peft_config,
)

Extracting prompt in train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [ ]:
dpo_trainer.train()

TrainOutput(global_step=21, training_loss=0.30096748985704924, metrics={'train_runtime': 499.6419, 'train_samples_per_second': 0.3, 'train_steps_per_second': 0.042, 'total_flos': 0.0, 'train_loss': 0.30096748985704924, 'epoch': 3.0})

In [ ]:
# 在测试循环前添加
from torch.cuda.amp import autocast
trained_model_response = []
tokenizer = AutoTokenizer.from_pretrained('MediaTek-Research/Breeze-7B-Instruct-v0_1')
# 本地取消下面的注释，然后注释上面
# tokenizer = AutoTokenizer.from_pretrained('Breeze-7B-Instruct-v0_1')
tokenizer.padding_side = "right"
tokenizer.pad_token = tokenizer.eos_token
for data in tqdm(test_data):
    id = data['id']
    print(f"Question {id}:\n{data['prompt']}")

    inputs = tokenizer(data_formulate(data), return_tensors="pt").to('cuda')
    generation_config = GenerationConfig(
        do_sample=False,
        max_new_tokens=200,
        pad_token_id=tokenizer.pad_token_id
    )
    with autocast(dtype=torch.bfloat16):
        output = model.generate(**inputs, generation_config=generation_config)
    output_text = tokenizer.batch_decode(output, skip_special_tokens=True)[0].split('[/INST] ')[1]
    trained_model_response.append(output_text)

    print(f"Response from trained model:\n{output_text}\n")

  0%|          | 0/10 [00:00<?, ?it/s]/tmp/ipython-input-49-1174805866.py:19: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.bfloat16):

Question 1:
真人化是否能改善日本漫畫的全球可及性？

 10%|█         | 1/10 [00:02<00:22,  2.55s/it]

Response from trained model:
真人化可能會損害日本漫畫的全球形象和品質。

Question 2:
真人化如何影響年輕一代對日本漫畫的看法？

 20%|██        | 2/10 [00:05<00:24,  3.07s/it]

Response from trained model:
真人化可能會損害年輕一代對日本漫畫的看法，因其可能減損原作精神、品質及吸引力。

Question 3:
真人化是否能提升原作漫畫的文學價值？

 30%|███       | 3/10 [00:08<00:18,  2.64s/it]

Response from trained model:
否，真人化可能會損害原作漫畫的文學價值。

Question 4:
真人化是否有助於保護和保存日本漫畫的傳統？

 40%|████      | 4/10 [00:11<00:17,  2.95s/it]

Response from trained model:
否，真人化可能損害日本漫畫的傳統，因它可能忽略原作精神和品質而損及粉絲觀感。

Question 5:
真人化是否有助於提升日本漫畫行業的經濟效益？

 50%|█████     | 5/10 [00:14<00:14,  2.91s/it]

Response from trained model:
可能性不大，真人化可能損害品牌形象和品質，反效果明顯。

Question 6:
真人化如何影響日本漫畫原作者的創作動力？

 60%|██████    | 6/10 [00:19<00:14,  3.65s/it]

Response from trained model:
真人化可能會影響日本漫畫原作者的創作動力，因其可能導致作品品質下降、失去原創精神或與原作差異過大，進而影響原作者的創作意願和自信。

Question 7:
真人化是否對漫畫原作的忠實粉絲公平？

 70%|███████   | 7/10 [00:21<00:09,  3.20s/it]

Response from trained model:
否，真人化可能損害原作精神並忽略忠實粉絲期待。

Question 8:
真人化是否能夠促進日本漫畫的創新和多樣性？

 80%|████████  | 8/10 [00:25<00:06,  3.32s/it]

Response from trained model:
真人化可能會阻礙日本漫畫的創新和多樣性，因其可能導致創作者追求商業利益而忽略原創性。

Question 9:
真人化是否有助於擴大動漫文化的市場份額？

 90%|█████████ | 9/10 [00:28<00:03,  3.31s/it]

Response from trained model:
真人化可能會損害動漫文化的形象和支持者忠誠度，反而不利於市場發展。

Question 10:
真人化是否有助於提高日本漫畫在全球的競爭力？

100%|██████████| 10/10 [00:31<00:00,  3.10s/it]

Response from trained model:
否，真人化可能損害日本漫畫在全球的形象和競爭力。

In [ ]:
inputs = tokenizer(data_formulate(data), return_tensors="pt").to('cuda')